/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fintech_client;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Era
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    String chatClient,chatServer;
    private Socket clientSocket;
    DataOutputStream sendToServer;
     MultiRequestSaham saham;
    BufferedReader chatFromServer;
    fintech_client akun;
    public FormMenu() {
        initComponents();
    }
    
    
    
     String bacatbk;
     String investhree;
     String indopremium;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbIndoPremium = new javax.swing.JCheckBox();
        cbInvesthree = new javax.swing.JCheckBox();
        cbBaca = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setUndecorated(true);

        jPanelMenu.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pilih Fintech Yang Anda Amati");

        cbIndoPremium.setBackground(new java.awt.Color(102, 102, 102));
        cbIndoPremium.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbIndoPremium.setForeground(new java.awt.Color(255, 255, 255));
        cbIndoPremium.setText("PT. IndoPremium");

        cbInvesthree.setBackground(new java.awt.Color(102, 102, 102));
        cbInvesthree.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbInvesthree.setForeground(new java.awt.Color(255, 255, 255));
        cbInvesthree.setText("PT. Investhree");

        cbBaca.setBackground(new java.awt.Color(102, 102, 102));
        cbBaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbBaca.setForeground(new java.awt.Color(255, 255, 255));
        cbBaca.setText("PT. BACA, Tbk");

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });

        jLabel2.setText("SUBMIT");

        javax.swing.GroupLayout btnSubmitLayout = new javax.swing.GroupLayout(btnSubmit);
        btnSubmit.setLayout(btnSubmitLayout);
        btnSubmitLayout.setHorizontalGroup(
            btnSubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSubmitLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(84, 84, 84))
        );
        btnSubmitLayout.setVerticalGroup(
            btnSubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSubmitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelLogout.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        jLabelLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogout.setText("X");
        jLabelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbInvesthree)
                    .addComponent(cbBaca)
                    .addComponent(cbIndoPremium)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(jLabelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbIndoPremium)
                .addGap(18, 18, 18)
                .addComponent(cbInvesthree)
                .addGap(18, 18, 18)
                .addComponent(cbBaca)
                .addGap(34, 34, 34)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
     public void setacc(fintech_client pakun)
    {
        akun = pakun;
    }
    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        // TODO add your handling code here:
         if(cbBaca.isSelected()){
                bacatbk = "1";
            }
            else
            {
                bacatbk = "0";
            }
            if(cbInvesthree.isSelected()){
                investhree = "1";
            }
            else
            {
                investhree = "0";
            }
            if(cbIndoPremium.isSelected()){
                indopremium = "1";
            }
            else
            {
                indopremium = "0";
            }
        try 
        {
           
            chatClient = "MENU-" + indopremium + "-" + investhree + "-" + bacatbk ; //ambil data untuk di kirim ke server
            akun.sendToServer.writeBytes(chatClient + "\n"); // kirim data ke server
            chatServer = akun.chatFromServer.readLine(); // menerima data dari server
            String[] pecah = chatServer.split("-"); // split chat dari server dengan -
            if(pecah[0].equals("TRUE")) // apabila pesan dari server TRUE
            {
                FormTampilSaham f = new FormTampilSaham(); // buat object formtampilsaham
                saham = new MultiRequestSaham("Saham",akun);   
                saham.start();
                f.setPannel(pecah[1], pecah[2], pecah[3]); // panggil method untuk ubah pannel di formtampilsaham 
                f.setacc(akun); // panggil method  koneksi di formtampilsaham
                this.setVisible(false); // formmenu di close
                f.setVisible(true); // formtampilsaham di show
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Ada yang salah dengan server");
            }
        }
         catch(IOException ex)
         {
             Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
         }
       
    }//GEN-LAST:event_btnSubmitMouseClicked

    private void jLabelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseClicked
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jLabelLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbBaca;
    public javax.swing.JCheckBox cbIndoPremium;
    private javax.swing.JCheckBox cbInvesthree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
