/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fintech_server;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.User;
/**
 *
 * @author Era
 */
public class Fintech_Server extends javax.swing.JFrame {

    /**
     * Creates new form ui_server
     */
     MainServer Server;
   
    public Fintech_Server() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelIndo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIndoEuro = new javax.swing.JTextField();
        jTextFieldIndoIhsg = new javax.swing.JTextField();
        jTextFieldIndoPounds = new javax.swing.JTextField();
        jTextFieldIndoUsd = new javax.swing.JTextField();
        jPanelInvest = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldInvesEuro = new javax.swing.JTextField();
        jTextFieldInvesUsd = new javax.swing.JTextField();
        jTextFieldInvesIhsg = new javax.swing.JTextField();
        jTextFieldInvesPounds = new javax.swing.JTextField();
        jPanelBaca = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldBacaEuro = new javax.swing.JTextField();
        jTextFieldBacaIhsg = new javax.swing.JTextField();
        jTextFieldBacaUsd = new javax.swing.JTextField();
        jTextFieldBacaPounds = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonDisconnect = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonConnect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jPanelIndo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("INDOPREMIUM");

        javax.swing.GroupLayout jPanelIndoLayout = new javax.swing.GroupLayout(jPanelIndo);
        jPanelIndo.setLayout(jPanelIndoLayout);
        jPanelIndoLayout.setHorizontalGroup(
            jPanelIndoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIndoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelIndoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldIndoUsd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIndoPounds, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIndoIhsg, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIndoEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelIndoLayout.setVerticalGroup(
            jPanelIndoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIndoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jTextFieldIndoUsd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jTextFieldIndoEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jTextFieldIndoPounds, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jTextFieldIndoIhsg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelIndo);
        jPanelIndo.setBounds(390, 0, 140, 480);

        jPanelInvest.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("INVESTHREE");

        javax.swing.GroupLayout jPanelInvestLayout = new javax.swing.GroupLayout(jPanelInvest);
        jPanelInvest.setLayout(jPanelInvestLayout);
        jPanelInvestLayout.setHorizontalGroup(
            jPanelInvestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInvestLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanelInvestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldInvesUsd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldInvesPounds, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldInvesIhsg, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldInvesEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        jPanelInvestLayout.setVerticalGroup(
            jPanelInvestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInvestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jTextFieldInvesUsd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jTextFieldInvesEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jTextFieldInvesPounds, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jTextFieldInvesIhsg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );

        jPanel1.add(jPanelInvest);
        jPanelInvest.setBounds(214, 0, 150, 480);

        jPanelBaca.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("BACA, TBK");

        javax.swing.GroupLayout jPanelBacaLayout = new javax.swing.GroupLayout(jPanelBaca);
        jPanelBaca.setLayout(jPanelBacaLayout);
        jPanelBacaLayout.setHorizontalGroup(
            jPanelBacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBacaLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanelBacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBacaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBacaLayout.createSequentialGroup()
                        .addGroup(jPanelBacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldBacaUsd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBacaPounds, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBacaIhsg, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBacaEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );
        jPanelBacaLayout.setVerticalGroup(
            jPanelBacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBacaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jTextFieldBacaUsd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jTextFieldBacaEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jTextFieldBacaPounds, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jTextFieldBacaIhsg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelBaca);
        jPanelBaca.setBounds(550, 0, 140, 480);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VALAS EURO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 180, 86, 21);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VALAS POUNDS");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 250, 107, 21);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("IHSG");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 320, 33, 21);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VALAS USD");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 110, 77, 21);

        jButtonDisconnect.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDisconnect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDisconnect.setForeground(new java.awt.Color(102, 102, 102));
        jButtonDisconnect.setText("Disconnect");
        jButtonDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisconnectActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDisconnect);
        jButtonDisconnect.setBounds(10, 50, 190, 30);

        jButtonSave.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(102, 102, 102));
        jButtonSave.setText("SAVE");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave);
        jButtonSave.setBounds(10, 420, 190, 40);

        jButtonConnect.setBackground(new java.awt.Color(255, 255, 255));
        jButtonConnect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonConnect.setForeground(new java.awt.Color(102, 102, 102));
        jButtonConnect.setText("Connect");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConnect);
        jButtonConnect.setBounds(10, 10, 190, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisconnectActionPerformed
        try {
           Server = new MainServer();
            Server.shutdown();
        } catch (IOException e) {
        }
    }//GEN-LAST:event_jButtonDisconnectActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        User user = new User();
        double invessUSD = Double.parseDouble(jTextFieldInvesUsd.getText());
        double invessEURO = Double.parseDouble(jTextFieldInvesEuro.getText());
        double invessPOUNDS = Double.parseDouble(jTextFieldInvesPounds.getText());
        double invessIHSG = Double.parseDouble(jTextFieldInvesIhsg.getText());
        user.insertSaham("Investhree", invessUSD , invessEURO, invessPOUNDS, invessIHSG);
        double indoUSD = Double.parseDouble(jTextFieldIndoUsd.getText());
        double indoEURO = Double.parseDouble(jTextFieldIndoEuro.getText());
        double indoPOUNDS = Double.parseDouble(jTextFieldIndoPounds.getText());
        double indoIHSG = Double.parseDouble(jTextFieldIndoIhsg.getText());
        user.insertSaham("IndoPremium", indoUSD , indoEURO, indoPOUNDS, indoIHSG);
        double bacaUSD = Double.parseDouble(jTextFieldBacaUsd.getText());
        double bacaEURO = Double.parseDouble(jTextFieldBacaEuro.getText());
        double bacaPOUNDS = Double.parseDouble(jTextFieldBacaPounds.getText());
        double bacaIHSG = Double.parseDouble(jTextFieldBacaIhsg.getText());
        user.insertSaham("Baca", bacaUSD , bacaEURO, bacaPOUNDS, bacaIHSG);   
        JOptionPane.showMessageDialog(null,"berhasil melakukan input");
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        // TODO add your handling code here:
         try {
           Server = new MainServer();
           Server.Active();
        } catch (IOException e) {
        }
    }//GEN-LAST:event_jButtonConnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fintech_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fintech_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fintech_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fintech_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fintech_Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonDisconnect;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBaca;
    private javax.swing.JPanel jPanelIndo;
    private javax.swing.JPanel jPanelInvest;
    private javax.swing.JTextField jTextFieldBacaEuro;
    private javax.swing.JTextField jTextFieldBacaIhsg;
    private javax.swing.JTextField jTextFieldBacaPounds;
    private javax.swing.JTextField jTextFieldBacaUsd;
    private javax.swing.JTextField jTextFieldIndoEuro;
    private javax.swing.JTextField jTextFieldIndoIhsg;
    private javax.swing.JTextField jTextFieldIndoPounds;
    private javax.swing.JTextField jTextFieldIndoUsd;
    private javax.swing.JTextField jTextFieldInvesEuro;
    private javax.swing.JTextField jTextFieldInvesIhsg;
    private javax.swing.JTextField jTextFieldInvesPounds;
    private javax.swing.JTextField jTextFieldInvesUsd;
    // End of variables declaration//GEN-END:variables
}
